In [1]:
import numpy as np
import pandas as pd

In [2]:
movies = pd.read_csv('tmdb_5000_movies.csv')
credit = pd.read_csv('tmdb_5000_credits.csv')

In [7]:
movies.head()

,budget,genres,homepage,id,keywords,original_language,original_title,overview,popularity,production_companies,production_countries,release_date,revenue,runtime,spoken_languages,status,tagline,title,vote_average,vote_count
0,237000000,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...",http://www.avatarmovie.com/,19995,"[{""id"": 1463, ""name"": ""culture clash""}, {""id"":...",en,Avatar,"In the 22nd century, a paraplegic Marine is di...",150.437577,"[{""name"": ""Ingenious Film Partners"", ""id"": 289...","[{""iso_3166_1"": ""US"", ""name"": ""United States o...",2009-12-10,2787965087,162.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}, {""iso...",Released,Enter the World of Pandora.,Avatar,7.2,11800
1,300000000,"[{""id"": 12, ""name"": ""Adventure""}, {""id"": 14, ""...",http://disney.go.com/disneypictures/pirates/,285,"[{""id"": 270, ""name"": ""ocean""}, {""id"": 726, ""na...",en,Pirates of the Caribbean: At World's End,"Captain Barbossa, long believed to be dead, ha...",139.082615,"[{""name"": ""Walt Disney Pictures"", ""id"": 2}, {""...","[{""iso_3166_1"": ""US"", ""name"": ""United States o...",2007-05-19,961000000,169.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}]",Released,"At the end of the world, the adventure begins.",Pirates of the Caribbean: At World's End,6.9,4500
2,245000000,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...",http://www.sonypictures.com/movies/spectre/,206647,"[{""id"": 470, ""name"": ""spy""}, {""id"": 818, ""name...",en,Spectre,A cryptic message from Bond’s past sends him o...,107.376788,"[{""name"": ""Columbia Pictures"", ""id"": 5}, {""nam...","[{""iso_3166_1"": ""GB"", ""name"": ""United Kingdom""...",2015-10-26,880674609,148.0,"[{""iso_639_1"": ""fr"", ""name"": ""Fran\u00e7ais""},...",Released,A Plan No One Escapes,Spectre,6.3,4466
3,250000000,"[{""id"": 28, ""name"": ""Action""}, {""id"": 80, ""nam...",http://www.thedarkknightrises.com/,49026,"[{""id"": 849, ""name"": ""dc comics""}, {""id"": 853,...",en,The Dark Knight Rises,Following the death of District Attorney Harve...,112.312950,"[{""name"": ""Legendary Pictures"", ""id"": 923}, {""...","[{""iso_3166_1"": ""US"", ""name"": ""United States o...",2012-07-16,1084939099,165.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}]",Released,The Legend Ends,The Dark Knight Rises,7.6,9106
4,260000000,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...",http://movies.disney.com/john-carter,49529,"[{""id"": 818, ""name"": ""based on novel""}, {""id"":...",en,John Carter,"John Carter is a war-weary, former military ca...",43.926995,"[{""name"": ""Walt Disney Pictures"", ""id"": 2}]","[{""iso_3166_1"": ""US"", ""name"": ""United States o...",2012-03-07,284139100,132.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}]",Released,"Lost in our world, found in another.",John Carter,6.1,2124

In [6]:
credit.head()

,movie_id,title,cast,crew
0,19995,Avatar,"[{""cast_id"": 242, ""character"": ""Jake Sully"", ""...","[{""credit_id"": ""52fe48009251416c750aca23"", ""de..."
1,285,Pirates of the Caribbean: At World's End,"[{""cast_id"": 4, ""character"": ""Captain Jack Spa...","[{""credit_id"": ""52fe4232c3a36847f800b579"", ""de..."
2,206647,Spectre,"[{""cast_id"": 1, ""character"": ""James Bond"", ""cr...","[{""credit_id"": ""54805967c3a36829b5002c41"", ""de..."
3,49026,The Dark Knight Rises,"[{""cast_id"": 2, ""character"": ""Bruce Wayne / Ba...","[{""credit_id"": ""52fe4781c3a36847f81398c3"", ""de..."
4,49529,John Carter,"[{""cast_id"": 5, ""character"": ""John Carter"", ""c...","[{""credit_id"": ""52fe479ac3a36847f813eaa3"", ""de..."

In [8]:
movies = movies.merge(credits,on='title')

TypeError: Can only merge Series or DataFrame objects, a <class '_sitebuiltins._Printer'> was passed

In [15]:
movies.head()

,budget,genres,homepage,id,keywords,original_language,original_title,overview,popularity,production_companies,...,runtime,spoken_languages,status,tagline,title,vote_average,vote_count,movie_id,cast,crew
0,237000000,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...",http://www.avatarmovie.com/,19995,"[{""id"": 1463, ""name"": ""culture clash""}, {""id"":...",en,Avatar,"In the 22nd century, a paraplegic Marine is di...",150.437577,"[{""name"": ""Ingenious Film Partners"", ""id"": 289...",...,162.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}, {""iso...",Released,Enter the World of Pandora.,Avatar,7.2,11800,19995,"[{""cast_id"": 242, ""character"": ""Jake Sully"", ""...","[{""credit_id"": ""52fe48009251416c750aca23"", ""de..."
1,300000000,"[{""id"": 12, ""name"": ""Adventure""}, {""id"": 14, ""...",http://disney.go.com/disneypictures/pirates/,285,"[{""id"": 270, ""name"": ""ocean""}, {""id"": 726, ""na...",en,Pirates of the Caribbean: At World's End,"Captain Barbossa, long believed to be dead, ha...",139.082615,"[{""name"": ""Walt Disney Pictures"", ""id"": 2}, {""...",...,169.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}]",Released,"At the end of the world, the adventure begins.",Pirates of the Caribbean: At World's End,6.9,4500,285,"[{""cast_id"": 4, ""character"": ""Captain Jack Spa...","[{""credit_id"": ""52fe4232c3a36847f800b579"", ""de..."
2,245000000,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...",http://www.sonypictures.com/movies/spectre/,206647,"[{""id"": 470, ""name"": ""spy""}, {""id"": 818, ""name...",en,Spectre,A cryptic message from Bond’s past sends him o...,107.376788,"[{""name"": ""Columbia Pictures"", ""id"": 5}, {""nam...",...,148.0,"[{""iso_639_1"": ""fr"", ""name"": ""Fran\u00e7ais""},...",Released,A Plan No One Escapes,Spectre,6.3,4466,206647,"[{""cast_id"": 1, ""character"": ""James Bond"", ""cr...","[{""credit_id"": ""54805967c3a36829b5002c41"", ""de..."
3,250000000,"[{""id"": 28, ""name"": ""Action""}, {""id"": 80, ""nam...",http://www.thedarkknightrises.com/,49026,"[{""id"": 849, ""name"": ""dc comics""}, {""id"": 853,...",en,The Dark Knight Rises,Following the death of District Attorney Harve...,112.312950,"[{""name"": ""Legendary Pictures"", ""id"": 923}, {""...",...,165.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}]",Released,The Legend Ends,The Dark Knight Rises,7.6,9106,49026,"[{""cast_id"": 2, ""character"": ""Bruce Wayne / Ba...","[{""credit_id"": ""52fe4781c3a36847f81398c3"", ""de..."
4,260000000,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...",http://movies.disney.com/john-carter,49529,"[{""id"": 818, ""name"": ""based on novel""}, {""id"":...",en,John Carter,"John Carter is a war-weary, former military ca...",43.926995,"[{""name"": ""Walt Disney Pictures"", ""id"": 2}]",...,132.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}]",Released,"Lost in our world, found in another.",John Carter,6.1,2124,49529,"[{""cast_id"": 5, ""character"": ""John Carter"", ""c...","[{""credit_id"": ""52fe479ac3a36847f813eaa3"", ""de..."

In [16]:
# movies selected columns:
# budget
# homepage
# id
# original_language
# original_title
# popularity
# production_comapny
# production_countries

In [17]:
movies = movies[['movie_id','title','overview','genres','keywords','cast','crew']]

In [18]:
movies.head()

,movie_id,title,overview,genres,keywords,cast,crew
0,19995,Avatar,"In the 22nd century, a paraplegic Marine is di...","[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...","[{""id"": 1463, ""name"": ""culture clash""}, {""id"":...","[{""cast_id"": 242, ""character"": ""Jake Sully"", ""...","[{""credit_id"": ""52fe48009251416c750aca23"", ""de..."
1,285,Pirates of the Caribbean: At World's End,"Captain Barbossa, long believed to be dead, ha...","[{""id"": 12, ""name"": ""Adventure""}, {""id"": 14, ""...","[{""id"": 270, ""name"": ""ocean""}, {""id"": 726, ""na...","[{""cast_id"": 4, ""character"": ""Captain Jack Spa...","[{""credit_id"": ""52fe4232c3a36847f800b579"", ""de..."
2,206647,Spectre,A cryptic message from Bond’s past sends him o...,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...","[{""id"": 470, ""name"": ""spy""}, {""id"": 818, ""name...","[{""cast_id"": 1, ""character"": ""James Bond"", ""cr...","[{""credit_id"": ""54805967c3a36829b5002c41"", ""de..."
3,49026,The Dark Knight Rises,Following the death of District Attorney Harve...,"[{""id"": 28, ""name"": ""Action""}, {""id"": 80, ""nam...","[{""id"": 849, ""name"": ""dc comics""}, {""id"": 853,...","[{""cast_id"": 2, ""character"": ""Bruce Wayne / Ba...","[{""credit_id"": ""52fe4781c3a36847f81398c3"", ""de..."
4,49529,John Carter,"John Carter is a war-weary, former military ca...","[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...","[{""id"": 818, ""name"": ""based on novel""}, {""id"":...","[{""cast_id"": 5, ""character"": ""John Carter"", ""c...","[{""credit_id"": ""52fe479ac3a36847f813eaa3"", ""de..."

In [19]:
movies.isnull().sum()

movie_id    0
title       0
overview    3
genres      0
keywords    0
cast        0
crew        0
dtype: int64

In [20]:
# dropping the data
movies.dropna(inplace=True)

In [21]:
movies.duplicated().sum() # no duplicate data

0

In [27]:
movies.iloc[0].genres

'[{"id": 28, "name": "Action"}, {"id": 12, "name": "Adventure"}, {"id": 14, "name": "Fantasy"}, {"id": 878, "name": "Science Fiction"}]'

In [50]:
import ast

# previously genre is in string of list so to convert it in only list we use 'ast.literal_eval' .

def convert_genre(obj):
    l = []
    for i in ast.literal_eval(obj):
        l.append(i['name'])
    return l

In [51]:
movies['genres'] = movies['genres'].apply(convert_genre)

ValueError: malformed node or string: ['Action', 'Adventure', 'Fantasy', 'Science Fiction']

In [52]:
movies.head()

,movie_id,title,overview,genres,keywords,cast,crew
0,19995,Avatar,"In the 22nd century, a paraplegic Marine is di...","[Action, Adventure, Fantasy, Science Fiction]","[culture clash, future, space war, space colon...","[{""cast_id"": 242, ""character"": ""Jake Sully"", ""...","[{""credit_id"": ""52fe48009251416c750aca23"", ""de..."
1,285,Pirates of the Caribbean: At World's End,"Captain Barbossa, long believed to be dead, ha...","[Adventure, Fantasy, Action]","[ocean, drug abuse, exotic island, east india ...","[{""cast_id"": 4, ""character"": ""Captain Jack Spa...","[{""credit_id"": ""52fe4232c3a36847f800b579"", ""de..."
2,206647,Spectre,A cryptic message from Bond’s past sends him o...,"[Action, Adventure, Crime]","[spy, based on novel, secret agent, sequel, mi...","[{""cast_id"": 1, ""character"": ""James Bond"", ""cr...","[{""credit_id"": ""54805967c3a36829b5002c41"", ""de..."
3,49026,The Dark Knight Rises,Following the death of District Attorney Harve...,"[Action, Crime, Drama, Thriller]","[dc comics, crime fighter, terrorist, secret i...","[{""cast_id"": 2, ""character"": ""Bruce Wayne / Ba...","[{""credit_id"": ""52fe4781c3a36847f81398c3"", ""de..."
4,49529,John Carter,"John Carter is a war-weary, former military ca...","[Action, Adventure, Science Fiction]","[based on novel, mars, medallion, space travel...","[{""cast_id"": 5, ""character"": ""John Carter"", ""c...","[{""credit_id"": ""52fe479ac3a36847f813eaa3"", ""de..."

In [53]:
movies['keywords'] = movies['keywords'].apply(convert_genre)

ValueError: malformed node or string: ['culture clash', 'future', 'space war', 'space colony', 'society', 'space travel', 'futuristic', 'romance', 'space', 'alien', 'tribe', 'alien planet', 'cgi', 'marine', 'soldier', 'battle', 'love affair', 'anti war', 'power relations', 'mind and soul', '3d']

In [46]:
movies.head()

,movie_id,title,overview,genres,keywords,cast,crew
0,19995,Avatar,"In the 22nd century, a paraplegic Marine is di...","[Action, Adventure, Fantasy, Science Fiction]","[culture clash, future, space war, space colon...","[{""cast_id"": 242, ""character"": ""Jake Sully"", ""...","[{""credit_id"": ""52fe48009251416c750aca23"", ""de..."
1,285,Pirates of the Caribbean: At World's End,"Captain Barbossa, long believed to be dead, ha...","[Adventure, Fantasy, Action]","[ocean, drug abuse, exotic island, east india ...","[{""cast_id"": 4, ""character"": ""Captain Jack Spa...","[{""credit_id"": ""52fe4232c3a36847f800b579"", ""de..."
2,206647,Spectre,A cryptic message from Bond’s past sends him o...,"[Action, Adventure, Crime]","[spy, based on novel, secret agent, sequel, mi...","[{""cast_id"": 1, ""character"": ""James Bond"", ""cr...","[{""credit_id"": ""54805967c3a36829b5002c41"", ""de..."
3,49026,The Dark Knight Rises,Following the death of District Attorney Harve...,"[Action, Crime, Drama, Thriller]","[dc comics, crime fighter, terrorist, secret i...","[{""cast_id"": 2, ""character"": ""Bruce Wayne / Ba...","[{""credit_id"": ""52fe4781c3a36847f81398c3"", ""de..."
4,49529,John Carter,"John Carter is a war-weary, former military ca...","[Action, Adventure, Science Fiction]","[based on novel, mars, medallion, space travel...","[{""cast_id"": 5, ""character"": ""John Carter"", ""c...","[{""credit_id"": ""52fe479ac3a36847f813eaa3"", ""de..."

In [54]:
movies.head()

,movie_id,title,overview,genres,keywords,cast,crew
0,19995,Avatar,"In the 22nd century, a paraplegic Marine is di...","[Action, Adventure, Fantasy, Science Fiction]","[culture clash, future, space war, space colon...","[{""cast_id"": 242, ""character"": ""Jake Sully"", ""...","[{""credit_id"": ""52fe48009251416c750aca23"", ""de..."
1,285,Pirates of the Caribbean: At World's End,"Captain Barbossa, long believed to be dead, ha...","[Adventure, Fantasy, Action]","[ocean, drug abuse, exotic island, east india ...","[{""cast_id"": 4, ""character"": ""Captain Jack Spa...","[{""credit_id"": ""52fe4232c3a36847f800b579"", ""de..."
2,206647,Spectre,A cryptic message from Bond’s past sends him o...,"[Action, Adventure, Crime]","[spy, based on novel, secret agent, sequel, mi...","[{""cast_id"": 1, ""character"": ""James Bond"", ""cr...","[{""credit_id"": ""54805967c3a36829b5002c41"", ""de..."
3,49026,The Dark Knight Rises,Following the death of District Attorney Harve...,"[Action, Crime, Drama, Thriller]","[dc comics, crime fighter, terrorist, secret i...","[{""cast_id"": 2, ""character"": ""Bruce Wayne / Ba...","[{""credit_id"": ""52fe4781c3a36847f81398c3"", ""de..."
4,49529,John Carter,"John Carter is a war-weary, former military ca...","[Action, Adventure, Science Fiction]","[based on novel, mars, medallion, space travel...","[{""cast_id"": 5, ""character"": ""John Carter"", ""c...","[{""credit_id"": ""52fe479ac3a36847f813eaa3"", ""de..."

In [55]:
def convert3(text):
    L = []
    counter = 0
    for i in ast.literal_eval(text):
        if counter < 3:
            L.append(i['name'])
        counter+=1
    return L

In [56]:
movies['cast'] = movies['cast'].apply(convert)
movies.head()

,movie_id,title,overview,genres,keywords,cast,crew
0,19995,Avatar,"In the 22nd century, a paraplegic Marine is di...","[Action, Adventure, Fantasy, Science Fiction]","[culture clash, future, space war, space colon...","[Sam Worthington, Zoe Saldana, Sigourney Weave...","[{""credit_id"": ""52fe48009251416c750aca23"", ""de..."
1,285,Pirates of the Caribbean: At World's End,"Captain Barbossa, long believed to be dead, ha...","[Adventure, Fantasy, Action]","[ocean, drug abuse, exotic island, east india ...","[Johnny Depp, Orlando Bloom, Keira Knightley, ...","[{""credit_id"": ""52fe4232c3a36847f800b579"", ""de..."
2,206647,Spectre,A cryptic message from Bond’s past sends him o...,"[Action, Adventure, Crime]","[spy, based on novel, secret agent, sequel, mi...","[Daniel Craig, Christoph Waltz, Léa Seydoux, R...","[{""credit_id"": ""54805967c3a36829b5002c41"", ""de..."
3,49026,The Dark Knight Rises,Following the death of District Attorney Harve...,"[Action, Crime, Drama, Thriller]","[dc comics, crime fighter, terrorist, secret i...","[Christian Bale, Michael Caine, Gary Oldman, A...","[{""credit_id"": ""52fe4781c3a36847f81398c3"", ""de..."
4,49529,John Carter,"John Carter is a war-weary, former military ca...","[Action, Adventure, Science Fiction]","[based on novel, mars, medallion, space travel...","[Taylor Kitsch, Lynn Collins, Samantha Morton,...","[{""credit_id"": ""52fe479ac3a36847f813eaa3"", ""de..."

In [57]:
def fetch_director(text):
    L = []
    for i in ast.literal_eval(text):
        if i['job'] == 'Director':
            L.append(i['name'])
    return L

In [58]:
movies['crew'] = movies['crew'].apply(fetch_director)

In [59]:
movies.head()

,movie_id,title,overview,genres,keywords,cast,crew
0,19995,Avatar,"In the 22nd century, a paraplegic Marine is di...","[Action, Adventure, Fantasy, Science Fiction]","[culture clash, future, space war, space colon...","[Sam Worthington, Zoe Saldana, Sigourney Weave...",[James Cameron]
1,285,Pirates of the Caribbean: At World's End,"Captain Barbossa, long believed to be dead, ha...","[Adventure, Fantasy, Action]","[ocean, drug abuse, exotic island, east india ...","[Johnny Depp, Orlando Bloom, Keira Knightley, ...",[Gore Verbinski]
2,206647,Spectre,A cryptic message from Bond’s past sends him o...,"[Action, Adventure, Crime]","[spy, based on novel, secret agent, sequel, mi...","[Daniel Craig, Christoph Waltz, Léa Seydoux, R...",[Sam Mendes]
3,49026,The Dark Knight Rises,Following the death of District Attorney Harve...,"[Action, Crime, Drama, Thriller]","[dc comics, crime fighter, terrorist, secret i...","[Christian Bale, Michael Caine, Gary Oldman, A...",[Christopher Nolan]
4,49529,John Carter,"John Carter is a war-weary, former military ca...","[Action, Adventure, Science Fiction]","[based on novel, mars, medallion, space travel...","[Taylor Kitsch, Lynn Collins, Samantha Morton,...",[Andrew Stanton]

In [61]:
movies['overview'][0]

'In the 22nd century, a paraplegic Marine is dispatched to the moon Pandora on a unique mission, but becomes torn between following orders and protecting an alien civilization.'

In [62]:
# as we can see that overview is a string, so we are converting overwiew to list.
movies['overview'] = movies['overview'].apply(lambda x:x.split())

In [63]:
movies .head()

,movie_id,title,overview,genres,keywords,cast,crew
0,19995,Avatar,"[In, the, 22nd, century,, a, paraplegic, Marin...","[Action, Adventure, Fantasy, Science Fiction]","[culture clash, future, space war, space colon...","[Sam Worthington, Zoe Saldana, Sigourney Weave...",[James Cameron]
1,285,Pirates of the Caribbean: At World's End,"[Captain, Barbossa,, long, believed, to, be, d...","[Adventure, Fantasy, Action]","[ocean, drug abuse, exotic island, east india ...","[Johnny Depp, Orlando Bloom, Keira Knightley, ...",[Gore Verbinski]
2,206647,Spectre,"[A, cryptic, message, from, Bond’s, past, send...","[Action, Adventure, Crime]","[spy, based on novel, secret agent, sequel, mi...","[Daniel Craig, Christoph Waltz, Léa Seydoux, R...",[Sam Mendes]
3,49026,The Dark Knight Rises,"[Following, the, death, of, District, Attorney...","[Action, Crime, Drama, Thriller]","[dc comics, crime fighter, terrorist, secret i...","[Christian Bale, Michael Caine, Gary Oldman, A...",[Christopher Nolan]
4,49529,John Carter,"[John, Carter, is, a, war-weary,, former, mili...","[Action, Adventure, Science Fiction]","[based on novel, mars, medallion, space travel...","[Taylor Kitsch, Lynn Collins, Samantha Morton,...",[Andrew Stanton]

In [65]:
# now we will remove all the spaces between the words in every column, this is to remove the confusion if the first names are same
def collapse(L):
    L1 = []
    for i in L:
        L1.append(i.replace(" ",""))
    return L1

In [66]:
movies['cast'] = movies['cast'].apply(collapse)
movies['crew'] = movies['crew'].apply(collapse)
movies['genres'] = movies['genres'].apply(collapse)
movies['keywords'] = movies['keywords'].apply(collapse)

In [67]:
movies.head()

,movie_id,title,overview,genres,keywords,cast,crew
0,19995,Avatar,"[In, the, 22nd, century,, a, paraplegic, Marin...","[Action, Adventure, Fantasy, ScienceFiction]","[cultureclash, future, spacewar, spacecolony, ...","[SamWorthington, ZoeSaldana, SigourneyWeaver, ...",[JamesCameron]
1,285,Pirates of the Caribbean: At World's End,"[Captain, Barbossa,, long, believed, to, be, d...","[Adventure, Fantasy, Action]","[ocean, drugabuse, exoticisland, eastindiatrad...","[JohnnyDepp, OrlandoBloom, KeiraKnightley, Ste...",[GoreVerbinski]
2,206647,Spectre,"[A, cryptic, message, from, Bond’s, past, send...","[Action, Adventure, Crime]","[spy, basedonnovel, secretagent, sequel, mi6, ...","[DanielCraig, ChristophWaltz, LéaSeydoux, Ralp...",[SamMendes]
3,49026,The Dark Knight Rises,"[Following, the, death, of, District, Attorney...","[Action, Crime, Drama, Thriller]","[dccomics, crimefighter, terrorist, secretiden...","[ChristianBale, MichaelCaine, GaryOldman, Anne...",[ChristopherNolan]
4,49529,John Carter,"[John, Carter, is, a, war-weary,, former, mili...","[Action, Adventure, ScienceFiction]","[basedonnovel, mars, medallion, spacetravel, p...","[TaylorKitsch, LynnCollins, SamanthaMorton, Wi...",[AndrewStanton]

In [68]:
movies['tags'] = movies['overview'] + movies['genres'] + movies['keywords'] + movies['cast'] + movies['crew']
# joing all the colums and creating tags

In [75]:
new = movies.drop(columns=['overview','genres','keywords','cast','crew'])
new.head()

,movie_id,title,tags
0,19995,Avatar,"[In, the, 22nd, century,, a, paraplegic, Marin..."
1,285,Pirates of the Caribbean: At World's End,"[Captain, Barbossa,, long, believed, to, be, d..."
2,206647,Spectre,"[A, cryptic, message, from, Bond’s, past, send..."
3,49026,The Dark Knight Rises,"[Following, the, death, of, District, Attorney..."
4,49529,John Carter,"[John, Carter, is, a, war-weary,, former, mili..."

In [76]:
new['tags'] = new['tags'].apply(lambda x: " ".join(x))
new.head()

,movie_id,title,tags
0,19995,Avatar,"In the 22nd century, a paraplegic Marine is di..."
1,285,Pirates of the Caribbean: At World's End,"Captain Barbossa, long believed to be dead, ha..."
2,206647,Spectre,A cryptic message from Bond’s past sends him o...
3,49026,The Dark Knight Rises,Following the death of District Attorney Harve...
4,49529,John Carter,"John Carter is a war-weary, former military ca..."

In [77]:
new['tags'] = new['tags'].apply(lambda x:x.lower())
new.head()

,movie_id,title,tags
0,19995,Avatar,"in the 22nd century, a paraplegic marine is di..."
1,285,Pirates of the Caribbean: At World's End,"captain barbossa, long believed to be dead, ha..."
2,206647,Spectre,a cryptic message from bond’s past sends him o...
3,49026,The Dark Knight Rises,following the death of district attorney harve...
4,49529,John Carter,"john carter is a war-weary, former military ca..."

In [78]:
!pip install nltk

Requirement already satisfied: nltk in c:\users\mihir\anaconda3\lib\site-packages (3.7)
Requirement already satisfied: joblib in c:\users\mihir\anaconda3\lib\site-packages (from nltk) (1.1.0)
Requirement already satisfied: click in c:\users\mihir\anaconda3\lib\site-packages (from nltk) (8.0.4)
Requirement already satisfied: regex>=2021.8.3 in c:\users\mihir\anaconda3\lib\site-packages (from nltk) (2022.3.15)
Requirement already satisfied: tqdm in c:\users\mihir\anaconda3\lib\site-packages (from nltk) (4.64.0)
Requirement already satisfied: colorama in c:\users\mihir\anaconda3\lib\site-packages (from click->nltk) (0.4.4)

In [82]:
# as we can see in tags there are words like 'loved', 'loving','love' but have the same meaning ' love' 
# so we will use'stem' to reducs the words

In [83]:
import nltk

In [84]:
from nltk.stem.porter import PorterStemmer
ps = PorterStemmer()

In [85]:
def stem(text):
    y = []
    for i in text.split():
        y.append(ps.stem(i))
    
    return " ".join(y)

In [86]:
new['tags'].apply(stem)

0       in the 22nd century, a parapleg marin is dispa...
1       captain barbossa, long believ to be dead, ha c...
2       a cryptic messag from bond’ past send him on a...
3       follow the death of district attorney harvey d...
4       john carter is a war-weary, former militari ca...
                              ...
4804    el mariachi just want to play hi guitar and ca...
4805    a newlyw couple' honeymoon is upend by the arr...
4806    "signed, sealed, delivered" introduc a dedic q...
4807    when ambiti new york attorney sam is sent to s...
4808    ever sinc the second grade when he first saw h...
Name: tags, Length: 4806, dtype: object

In [87]:
new.head()

,movie_id,title,tags
0,19995,Avatar,"in the 22nd century, a paraplegic marine is di..."
1,285,Pirates of the Caribbean: At World's End,"captain barbossa, long believed to be dead, ha..."
2,206647,Spectre,a cryptic message from bond’s past sends him o...
3,49026,The Dark Knight Rises,following the death of district attorney harve...
4,49529,John Carter,"john carter is a war-weary, former military ca..."

In [90]:
from sklearn.feature_extraction.text import CountVectorizer
cv = CountVectorizer(max_features = 2000, stop_words = 'english')

In [92]:
vectors = cv.fit_transform(new['tags']).toarray()

In [100]:
vectors

array([[0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       ...,
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]], dtype=int64)

In [101]:
cv.get_feature_names() # "get_feature_names" is use to find all the 2000 vector word
#  Use of "stem" helped here as both "acotr" and "actors" will be converted to"actor"

['000',
 '10',
 '11',
 '12',
 '15',
 '1930s',
 '1950s',
 '1960s',
 '1970s',
 '1980s',
 '19thcentury',
 '20',
 '30',
 '3d',
 'aaroneckhart',
 'abandoned',
 'ability',
 'able',
 'abuse',
 'academy',
 'accident',
 'accidentally',
 'act',
 'action',
 'actor',
 'actress',
 'actually',
 'adam',
 'adamsandler',
 'adaptation',
 'addiction',
 'adoption',
 'adultery',
 'adventure',
 'adventures',
 'advice',
 'affair',
 'africa',
 'african',
 'aftercreditsstinger',
 'afterlife',
 'age',
 'agent',
 'agents',
 'aging',
 'ago',
 'agrees',
 'ahead',
 'aid',
 'air',
 'airplane',
 'airport',
 'alanarkin',
 'alantudyk',
 'alaska',
 'alcohol',
 'alcoholic',
 'alcoholism',
 'alecbaldwin',
 'alex',
 'alfredmolina',
 'alice',
 'alien',
 'alieninvasion',
 'aliens',
 'alive',
 'allisonjanney',
 'alpacino',
 'alter',
 'amandapeet',
 'ambitious',
 'america',
 'american',
 'americanfootball',
 'americans',
 'amnesia',
 'amp',
 'amyadams',
 'ancient',
 'anderson',
 'android',
 'andy',
 'andygarcía',
 'andyserkis',
 'angel',
 'angeles',
 'angelinajolie',
 'animal',
 'animals',
 'animated',
 'animation',
 'anna',
 'annafaris',
 'anne',
 'annefletcher',
 'annehathaway',
 'annie',
 'annual',
 'answers',
 'anthonyanderson',
 'anthonyhopkins',
 'anthonymackie',
 'anti',
 'antoniobanderas',
 'apart',
 'apartment',
 'apocalypse',
 'apocalyptic',
 'appears',
 'area',
 'armed',
 'army',
 'arnoldschwarzenegger',
 'arrest',
 'arrested',
 'arrival',
 'arrive',
 'arrives',
 'art',
 'arthur',
 'artificialintelligence',
 'artist',
 'arts',
 'asks',
 'aspiring',
 'assassin',
 'assassination',
 'assigned',
 'assignment',
 'assistant',
 'astronaut',
 'attack',
 'attempt',
 'attempts',
 'attorney',
 'aunt',
 'australia',
 'author',
 'authorities',
 'away',
 'baby',
 'bachelor',
 'bad',
 'balance',
 'band',
 'bank',
 'bar',
 'barry',
 'baseball',
 'based',
 'basedoncomicbook',
 'basedonnovel',
 'basedontruestory',
 'basedonvideogame',
 'basedonyoungadultnovel',
 'basketball',
 'battle',
 'beach',
 'bear',
 'beat',
 'beautiful',
 'beauty',
 'befriends',
 'begin',
 'beginning',
 'begins',
 'believe',
 'believes',
 'beloved',
 'ben',
 'benaffleck',
 'beniciodeltoro',
 'benkingsley',
 'benstiller',
 'berlin',
 'best',
 'bestfriend',
 'bet',
 'bethgrant',
 'betrayal',
 'better',
 'big',
 'biggest',
 'billhader',
 'billmurray',
 'billnighy',
 'billpaxton',
 'billpullman',
 'billy',
 'billybobthornton',
 'biography',
 'birth',
 'birthday',
 'bizarre',
 'black',
 'blackmail',
 'blackpeople',
 'blind',
 'blood',
 'bloody',
 'boat',
 'bob',
 'bobbalaban',
 'bobby',
 'bobhoskins',
 'body',
 'bomb',
 'bond',
 'book',
 'born',
 'boss',
 'boston',
 'bounty',
 'box',
 'boxer',
 'boxing',
 'boy',
 'boyfriend',
 'boys',
 'bradleycooper',
 'bradpitt',
 'break',
 'breaks',
 'brendangleeson',
 'brian',
 'briancox',
 'bride',
 'bridge',
 'brien',
 'brilliant',
 'bring',
 'brings',
 'british',
 'broken',
 'brooklyn',
 'brother',
 'brotherbrotherrelationship',
 'brothers',
 'brothersisterrelationship',
 'brought',
 'brown',
 'bruce',
 'brucecampbell',
 'brucegreenwood',
 'brucemcgill',
 'brucewillis',
 'brutal',
 'buddy',
 'build',
 'building',
 'bus',
 'bush',
 'business',
 'businessman',
 'cabin',
 'california',
 'called',
 'calls',
 'came',
 'camerondiaz',
 'camp',
 'campaign',
 'campus',
 'canada',
 'cancer',
 'captain',
 'capture',
 'captured',
 'car',
 'carchase',
 'carcrash',
 'care',
 'career',
 'carlagugino',
 'carrie',
 'carter',
 'caryelwes',
 'case',
 'caseyaffleck',
 'cash',
 'casino',
 'cast',
 'castle',
 'cat',
 'cateblanchett',
 'catherinekeener',
 'catholic',
 'caught',
 'cause',
 'cave',
 'cedrictheentertainer',
 'celebration',
 'celiaweston',
 'center',
 'centered',
 'century',
 'certain',
 'chain',
 'challenge',
 'champion',
 'chance',
 'change',
 'changes',
 'changing',
 'channingtatum',
 'chaos',
 'character',
 'characters',
 'charles',
 'charlesdance',
 'charlie',
 'charliesheen',
 'charlizetheron',
 'chase',
 'cheating',
 'cheechmarin',
 'chicago',
 'chief',
 'child',
 'childhood',
 'children',
 'china',
 'chinese',
 'chloëgracemoretz',
 'choice',
 'choose',
 'chris',
 'chriscooper',
 'chrisrock',
 'christian',
 'christianbale',
 'christianslater',
 'christmas',
 'christopherlloyd',
 'christopherplummer',
 'christopherwalken',
 'church',
 'cia',
 'ciaránhinds',
 'circus',
 'city',
 'civil',
 'clarkgregg',
 'class',
 'classic',
 'clear',
 'cliftoncollinsjr',
 'clinteastwood',
 'clone',
 'clorisleachman',
 'close',
 'closer',
 'club',
 'clues',
 'coach',
 'cocaine',
 'code',
 'cold',
 'cole',
 'colinfarrell',
 'colinfirth',
 'college',
 'collide',
 'coma',
 'combat',
 'come',
 'comedy',
 'comes',
 'comic',
 'coming',
 'comingofage',
 'common',
 'community',
 'company',
 'compete',
 'competition',
 'complete',
 'complicated',
 'computer',
 'concert',
 'conflict',
 'confront',
 'connell',
 'connor',
 'consequences',
 'conspiracy',
 'contact',
 'continue',
 'continues',
 'control',
 'convict',
 'convinced',
 'convinces',
 'cook',
 'cop',
 'cops',
 'corporate',
 'corporation',
 'corrupt',
 'corruption',
 'count',
 'country',
 'countryside',
 'couple',
 'courage',
 'course',
 'court',
 'cousin',
 'cover',
 'crash',
 'crazy',
 'create',
 'created',
 'creates',
 'creature',
 'creatures',
 'crew',
 'crime',
 'crimes',
 'criminal',
 'criminals',
 'crisis',
 'cross',
 'crush',
 'cubagoodingjr',
 'cult',
 'culture',
 'curse',
 'dad',
 'daily',
 'danaykroyd',
 'dance',
 'dancer',
 'dancing',
 'danger',
 'dangerous',
 'danhedaya',
 'danielcraig',
 'danny',
 'dannydevito',
 'dannyglover',
 'dannytrejo',
 'dark',
 'darkcomedy',
 'darkness',
 'date',
 'dating',
 'daughter',
 'daughters',
 'david',
 'davidcross',
 'davidkoechner',
 'davidmorse',
 'davidpaymer',
 'davidthewlis',
 'davis',
 'day',
 'days',
 'dccomics',
 'dead',
 'deadly',
 'deal',
 'dealer',
 'dealing',
 'death',
 'debt',
 'deception',
 'decide',
 'decides',
 'deep',
 'defeat',
 'defense',
 'demon',
 'demons',
 'dennishopper',
 'dennisquaid',
 'denzelwashington',
 'depression',
 'dermotmulroney',
 'desert',
 'desire',
 'desperate',
 'desperately',
 'despite',
 'destiny',
 'destroy',
 'destroyed',
 'destruction',
 'detective',
 'determined',
 'detroit',
 'develops',
 'devil',
 'diamond',
 'dianekeaton',
 'did',
 'die',
 'died',
 'dies',
 'different',
 'difficult',
 'diner',
 'dinosaur',
 'directed',
 'director',
 'disappearance',
 'disaster',
 'discover',
 'discovers',
 'discovery',
 'disease',
 'distant',
 'district',
 'divorce',
 'doctor',
 'documentary',
 'does',
 'doesn',
 'dog',
 'doing',
 'don',
 'donaldsutherland',
 'doncheadle',
 'donnell',
 'door',
 'double',
 'dr',
 'dragon',
 'drama',
 'drawn',
 'dream',
 'dreams',
 'drewbarrymore',
 'drinking',
 'drive',
 'driven',
 'driver',
 'drug',
 'drugdealer',
 'drugs',
 'duo',
 'duringcreditsstinger',
 'dustinhoffman',
 'duty',
 'dwaynejohnson',
 'dying',
 'dyinganddeath',
 'dylanbaker',
 'dystopia',
 'early',
 'earth',
 'east',
 'easy',
 'eccentric',
 'eddie',
 'eddiemurphy',
 'edharris',
 'edward',
 'edwardnorton',
 'effort',
 'efforts',
 'egypt',
 'elderly',
 'eliaskoteas',
 'elijahwood',
 'elite',
 'elizabeth',
 'elizabethbanks',
 'embark',
 'embarks',
 'emilymortimer',
 'emma',
 'emmathompson',
 'emperor',
 'empire',
 'encounter',
 'encounters',
 'end',
 'ends',
 'enemies',
 'enemy',
 'england',
 'english',
 'enter',
 'enters',
 'entire',
 'epic',
 'escape',
 'escaped',
 'escapes',
 'especially',
 'espionage',
 'estate',
 'estranged',
 'ethanhawke',
 'eugenelevy',
 'europe',
 'evamendes',
 'eve',
 'event',
 'events',
 'eventually',
 'evidence',
 'evil',
 'ewanmcgregor',
 'ex',
 'exactly',
 'executive',
 'existence',
 'experience',
 'experiences',
 'experiment',
 'expert',
 'explosion',
 'explosive',
 'extramaritalaffair',
 'extraordinary',
 'eye',
 'eyes',
 'face',
 'faced',
 'faces',
 'facing',
 'failed',
 'fairy',
 'fairytale',
 'faith',
 'fall',
 'falling',
 'fallinginlove',
 'falls',
 'fame',
 'families',
 'family',
 'familyrelationships',
 'famkejanssen',
 'famous',
 'fantasy',
 'far',
 'farm',
 'farmer',
 'fast',
 'fat',
 'fate',
 'father',
 'fatherdaughterrelationship',
 'fathersonrelationship',
 'fbi',
 'fbiagent',
 'fear',
 'fears',
 'fellow',
 'female',
 'femalenudity',
 'fight',
 'fighter',
 'fighting',
 'fights',
 'figure',
 'filled',
 'film',
 'filmmaker',
 'films',
 'final',
 'finally',
 'financial',
 'finding',
 'finds',
 'finish',
 'flashback',
 'flight',
 'florida',
 'fly',
 'flying',
 'follow',
 'following',
 'follows',
 'food',
 'football',
 'force',
 'forced',
 'forces',
 'foreign',
 'forest',
 'forestwhitaker',
 'forever',
 'form',
 'fortune',
 'foster',
 'foundfootage',
 'fox',
 'framed',
 'france',
 'francisco',
 'frank',
 'frankoz',
 'frankwelker',
 'free',
 'freedom',
 'french',
 'friend',
 'friends',
 'friendship',
 'fugitive',
 'fun',
 'funeral',
 'future',
 'futuristic',
 'gainey',
 'galaxy',
 'gambling',
 'game',
 'games',
 'gang',
 'gangster',
 'garyoldman',
 'gay',
 'genehackman',
 'general',
 'genius',
 'geoffreyrush',
 'george',
 'georgeclooney',
 'gerardbutler',
 'german',
 'germany',
 'gets',
 'getting',
 'ghost',
 'giant',
 'gift',
 'giovanniribisi',
 'girl',
 'girlfriend',
 'girls',
 'given',
 'gives',
 'global',
 'god',
 'goes',
 'going',
 'gold',
 'gone',
 'good',
 'goodvsevil',
 'gore',
 'got',
 'government',
 'grace',
 'graduation',
 'grandfather',
 'grant',
 'great',
 'greatest',
 'green',
 'gregkinnear',
 'griffin',
 'group',
 'growing',
 'grown',
 'grows',
 'gruesome',
 'guard',
 'guilt',
 'gun',
 'gunfight',
 'guy',
 'guys',
 'gwynethpaltrow',
 'hacker',
 'half',
 'hall',
 'halloween',
 'hallucination',
 'hand',
 'hands',
 'handsome',
 'hankazaria',
 'happen',
 'happened',
 'happens',
 'happiness',
 'happy',
 'hara',
 'hard',
 'hare',
 'harrisonford',
 'harry',
 'harrydeanstanton',
 'harveykeitel',
 'haunted',
 'haunting',
 'having',
 'head',
 'heads',
 'heart',
 'heist',
 'held',
 'helen',
 'helenabonhamcarter',
 'helenmirren',
 'helicopter',
 'hell',
 'help',
 'helping',
 'henry',
 'hero',
 'heroes',
 'hidden',
 'hiding',
 'high',
 'highly',
 'highschool',
 'hill',
 'hip',
 'hired',
 'hires',
 'historicalfigure',
 'history',
 'hit',
 'hitman',
 'hits',
 'ho',
 'hold',
 'holds',
 'holiday',
 'hollywood',
 'home',
 'hometown',
 'homicide',
 'homosexuality',
 'hong',
 'honor',
 'hop',
 'hope',
 'hopes',
 'hoping',
 'horrific',
 'horror',
 'horse',
 'hospital',
 'host',
 'hostage',
 'hot',
 'hotel',
 'hours',
 'house',
 'huge',
 'hughes',
 'hughjackman',
 'hugoweaving',
 'human',
 'humanity',
 'humans',
 'hunt',
 'hunter',
 'husband',
 'ianholm',
 'ice',
 'icecube',
 'idea',
 'identity',
 'idriselba',
 'ii',
 'ill',
 'illegal',
 'illness',
 'imax',
 'immediately',
 'immigrant',
 'important',
 'impossible',
 'including',
 'increasingly',
 'incredible',
 'independentfilm',
 'india',
 'indian',
 'individual',
 'industry',
 'infidelity',
 'influence',
 'inner',
 'innocent',
 'insanity',
 'inside',
 'inspired',
 'instead',
 'intelligence',
 'international',
 'interview',
 'invasion',
 'inventor',
 'investigate',
 'investigates',
 'investigation',
 'involved',
 'involving',
 'iraq',
 'irish',
 'island',
 'isn',
 'isolated',
 'italian',
 'italy',
 'jack',
 'jackblack',
 'jackiechan',
 'jackson',
 'jail',
 'jake',
 'jakegyllenhaal',
 'james',
 'jamescaan',
 'jamescromwell',
 'jamesfranco',
 'jamesmarsden',
 'jamesremar',
 'jameswoods',
 'jamiefoxx',
 'jane',
 'janelynch',
 'japan',
 'japanese',
 'jason',
 'jasonbateman',
 'jasonflemyng',
 'jasonisaacs',
 'jasonlee',
 'jasonstatham',
 'jealousy',
 'jean',
 'jeffbridges',
 'jeffdaniels',
 'jeffreytambor',
 'jeffreywright',
 'jenamalone',
 'jenniferaniston',
 'jennifercoolidge',
 'jenniferlopez',
 'jeremypiven',
 'jessicaalba',
 'jesus',
 'jewish',
 'jim',
 'jimbroadbent',
 'jimcarrey',
 'jimmy',
 'joancusack',
 'job',
 'joe',
 'john',
 'johnc',
 'johncho',
 'johncleese',
 'johncusack',
 'johngoodman',
 'johnhurt',
 'johnleguizamo',
 'johnmalkovich',
 'johnmichaelhiggins',
 'johnny',
 'johnnydepp',
 'johnratzenberger',
 'johnson',
 'johntravolta',
 'johnturturro',
 'join',
 'joins',
 'jonahhill',
 'jonathan',
 'jones',
 'jonfavreau',
 'jonlovitz',
 'jonvoight',
 'jordan',
 'joshbrolin',
 'journalist',
 'journey',
 'jr',
 'judelaw',
 'judge',
 'judidench',
 'judygreer',
 'juliannemoore',
 'juliaroberts',
 'jungle',
 'just',
 'justice',
 'justinlong',
 'kate',
 'katewinslet',
 'kathybates',
 'keanureeves',
 'keithdavid',
 'kelly',
 'kenjeong',
 'kevin',
 'kevinbacon',
 'kevincostner',
 ...]

In [103]:
# to give the recommendation we will give the 5 neartest vectors
# to find the neartest vectors we will find distance
# to find distance we will use 'cosine distance' not 'eucledian distance' as vectors in angles
from sklearn.metrics.pairwise import cosine_similarity

In [108]:
similarity = cosine_similarity(vectors)
similarity.shape
# "cosine_similarity" will give the distance in telling who is more similar(1-0)

(4806, 4806)

In [105]:
# we got all the distances from aal the movie vectors

In [109]:
similarity[0]

array([1.        , 0.10400629, 0.06804138, ..., 0.03125   , 0.03125   ,
       0.        ])

In [119]:
def recommend(movie):
    movie_index = new[new['title']==movie].index[0]
    distances = similarity[movie_index]
    movie_list = sorted(list(enumerate(distances)),reverse = True,key = lambda x:x[1])[1:6]
    
    for i in movie_list:
        print(new_df.iloc[i[0]].title)

In [122]:
recommend("Avatar")

Aliens vs Predator: Requiem
Independence Day
Falcon Rising
Small Soldiers
Lifeforce

In [123]:
import pickle

In [124]:
pickle.dump(new,open('movies.pkl','wb'))

In [125]:
new['title'].values

array(['Avatar', "Pirates of the Caribbean: At World's End", 'Spectre',
       ..., 'Signed, Sealed, Delivered', 'Shanghai Calling',
       'My Date with Drew'], dtype=object)

In [128]:
pickle.dump(new.to_dict(),open('movie_dict.pkl','wb'))

In [129]:
pickle.dump(similarity,open('similarity.pkl','wb'))